[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "wrap_help"] }       # 命令行参数分析器
tokio = { version = "1.38.0", features = ["rt-multi-thread", "full"] }

cidr = { version = "0.2.2" } # 用于处理网络中的ip与host
